name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: gvt
      run: |
        go get github.com/polaris1119/gvt
        go install github.com/polaris1119/gvt
        ls /opt/hostedtoolcache/go/1.12.9/x64/bin

    - name: Get dependencies
      run: sh getpkg.sh

    - name: Build
      run: sh install.sh
